/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author jesus
 */
public class GestionCobertura extends javax.swing.JFrame {

    /**
     * Creates new form GestionCobertura
     */
    public GestionCobertura() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtexcodcob = new javax.swing.JTextField();
        btnbuscar = new javax.swing.JButton();
        butguardarcober = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        buteliminarcober = new javax.swing.JButton();
        butconsultarcober = new javax.swing.JButton();
        butsalircober = new javax.swing.JButton();
        jCmbServ = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableServicios = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jbtnagregar = new javax.swing.JButton();
        jBtnRemover = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jtxttotal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(647, 489));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setText("Gestión de Cobertura");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(220, 20, 191, 22);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("TOTAL");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(260, 570, 50, 17);

        jtexcodcob.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        getContentPane().add(jtexcodcob);
        jtexcodcob.setBounds(180, 180, 81, 23);

        btnbuscar.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Botones/Estaticos/Buscar.png"))); // NOI18N
        btnbuscar.setText("buscar");
        btnbuscar.setBorder(null);
        btnbuscar.setBorderPainted(false);
        btnbuscar.setContentAreaFilled(false);
        btnbuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnbuscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnbuscar.setIconTextGap(-3);
        btnbuscar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Botones/Pequeños/Buscarpeque.png"))); // NOI18N
        btnbuscar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Botones/Grandes/Buscargrande.png"))); // NOI18N
        btnbuscar.setVerifyInputWhenFocusTarget(false);
        btnbuscar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnbuscar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(btnbuscar);
        btnbuscar.setBounds(270, 160, 61, 70);

        butguardarcober.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        butguardarcober.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Botones/Estaticos/guardar.png"))); // NOI18N
        butguardarcober.setText("guardar");
        butguardarcober.setActionCommand("Guardar");
        butguardarcober.setBorder(null);
        butguardarcober.setBorderPainted(false);
        butguardarcober.setContentAreaFilled(false);
        butguardarcober.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        butguardarcober.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        butguardarcober.setIconTextGap(-3);
        butguardarcober.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Botones/Pequeños/Guardarpeque.png"))); // NOI18N
        butguardarcober.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Botones/Grandes/Buscargran.png"))); // NOI18N
        butguardarcober.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        butguardarcober.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(butguardarcober);
        butguardarcober.setBounds(90, 70, 61, 71);

        btnModificar.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Botones/Estaticos/Modificar.png"))); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.setBorder(null);
        btnModificar.setBorderPainted(false);
        btnModificar.setContentAreaFilled(false);
        btnModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnModificar.setIconTextGap(-3);
        btnModificar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Botones/Pequeños/Modificarpeque.png"))); // NOI18N
        btnModificar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Botones/Grandes/MoificarGrande.png"))); // NOI18N
        btnModificar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnModificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(btnModificar);
        btnModificar.setBounds(180, 70, 79, 70);

        buteliminarcober.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        buteliminarcober.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Botones/Estaticos/Eliminar.png"))); // NOI18N
        buteliminarcober.setText("eliminar");
        buteliminarcober.setBorder(null);
        buteliminarcober.setBorderPainted(false);
        buteliminarcober.setContentAreaFilled(false);
        buteliminarcober.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buteliminarcober.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buteliminarcober.setIconTextGap(-3);
        buteliminarcober.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Botones/Pequeños/eliminarchiquito.png"))); // NOI18N
        buteliminarcober.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Botones/Grandes/eliminargrande.png"))); // NOI18N
        buteliminarcober.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        buteliminarcober.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(buteliminarcober);
        buteliminarcober.setBounds(380, 70, 61, 70);

        butconsultarcober.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        butconsultarcober.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Botones/Estaticos/Consultar.png"))); // NOI18N
        butconsultarcober.setText("Consultar");
        butconsultarcober.setActionCommand("consultar");
        butconsultarcober.setBorder(null);
        butconsultarcober.setBorderPainted(false);
        butconsultarcober.setContentAreaFilled(false);
        butconsultarcober.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        butconsultarcober.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        butconsultarcober.setIconTextGap(-3);
        butconsultarcober.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Botones/Pequeños/Consultarpeque.png"))); // NOI18N
        butconsultarcober.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Botones/Grandes/consultargrand.png"))); // NOI18N
        butconsultarcober.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        butconsultarcober.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(butconsultarcober);
        butconsultarcober.setBounds(290, 70, 61, 70);

        butsalircober.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        butsalircober.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Botones/Estaticos/Salir.png"))); // NOI18N
        butsalircober.setText("salir");
        butsalircober.setBorder(null);
        butsalircober.setBorderPainted(false);
        butsalircober.setContentAreaFilled(false);
        butsalircober.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        butsalircober.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        butsalircober.setIconTextGap(-3);
        butsalircober.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Botones/Pequeños/Salirpeque.png"))); // NOI18N
        butsalircober.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Botones/Grandes/Salirgrande.png"))); // NOI18N
        butsalircober.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        butsalircober.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        butsalircober.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butsalircoberActionPerformed(evt);
            }
        });
        getContentPane().add(butsalircober);
        butsalircober.setBounds(480, 70, 61, 70);

        getContentPane().add(jCmbServ);
        jCmbServ.setBounds(260, 290, 230, 20);

        jTableServicios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableServicios);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(60, 410, 570, 130);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Código");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(120, 180, 50, 17);

        jbtnagregar.setText("Agregar");
        getContentPane().add(jbtnagregar);
        jbtnagregar.setBounds(260, 350, 73, 23);

        jBtnRemover.setText("Eliminar");
        getContentPane().add(jBtnRemover);
        jBtnRemover.setBounds(370, 350, 69, 23);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Servicios");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(160, 290, 80, 17);

        jtxttotal.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        getContentPane().add(jtxttotal);
        jtxttotal.setBounds(330, 570, 130, 23);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Fondo Grande.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 730, 660);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(70, 50, 510, 100);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butsalircoberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butsalircoberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_butsalircoberActionPerformed

    
    public JButton getBtnModificar() {
        return btnModificar;
    }

    public JButton getButcodcob() {
        return btnbuscar;
    }

    public JButton getButconsultarcober() {
        return butconsultarcober;
    }

    public JButton getButeliminarcober() {
        return buteliminarcober;
    }

    public JButton getButguardarcober() {
        return butguardarcober;
    }

    public JButton getButsalircober() {
        return butsalircober;
    }

    public JTable getjTableServicios() {
        return jTableServicios;
    }

    /**
     * @param args the command line arguments
     */
    public JTextField getJtexcodcob() {    
        return jtexcodcob;
    }

    public JButton getjBtnRemover() {
        return jBtnRemover;
    }

    public JComboBox<String> getjCmbServ() {
        return jCmbServ;
    }

    public JButton getJbtnagregar() {
        return jbtnagregar;
    }

    public JTextField getJtxttotal() {
        return jtxttotal;
    }

    public JButton getBtnbuscar() {
        return btnbuscar;
    }
    
    public void agregarListener(ActionListener accion) 
    {
        this.btnModificar.addActionListener(accion);
        this.jbtnagregar.addActionListener(accion);
        this.butconsultarcober.addActionListener(accion);
        this.butconsultarcober.addActionListener(accion);
        this.butguardarcober.addActionListener(accion);
        this.butsalircober.addActionListener(accion);
        this.jBtnRemover.addActionListener(accion);
        this.btnbuscar.addActionListener(accion);
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
        */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionCobertura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionCobertura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionCobertura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionCobertura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionCobertura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnModificar;
    public javax.swing.JButton btnbuscar;
    public javax.swing.JButton butconsultarcober;
    public javax.swing.JButton buteliminarcober;
    public javax.swing.JButton butguardarcober;
    public javax.swing.JButton butsalircober;
    private javax.swing.JButton jBtnRemover;
    private javax.swing.JComboBox<String> jCmbServ;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableServicios;
    private javax.swing.JButton jbtnagregar;
    public javax.swing.JTextField jtexcodcob;
    private javax.swing.JTextField jtxttotal;
    // End of variables declaration//GEN-END:variables
}
