/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author jesus
 */
public class GestionLogin extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public GestionLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTxtUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboRoll = new javax.swing.JComboBox<>();
        jTxtContraseña = new javax.swing.JPasswordField();
        jBtnIngresar = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(609, 480));
        setMinimumSize(new java.awt.Dimension(609, 480));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Cédula");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(190, 120, 49, 17);

        jTxtUsuario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        getContentPane().add(jTxtUsuario);
        jTxtUsuario.setBounds(250, 120, 110, 23);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Contraseña");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(160, 160, 90, 17);

        jComboRoll.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jComboRoll.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Analista", "Administrador" }));
        jComboRoll.setOpaque(false);
        getContentPane().add(jComboRoll);
        jComboRoll.setBounds(250, 210, 115, 23);

        jTxtContraseña.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        getContentPane().add(jTxtContraseña);
        jTxtContraseña.setBounds(250, 160, 110, 23);

        jBtnIngresar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnIngresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Botones/Estaticos/entrar.png"))); // NOI18N
        jBtnIngresar.setText("Entrar");
        jBtnIngresar.setBorder(null);
        jBtnIngresar.setBorderPainted(false);
        jBtnIngresar.setContentAreaFilled(false);
        jBtnIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnIngresar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnIngresar.setIconTextGap(-3);
        jBtnIngresar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Botones/Pequeños/entrarchiquito.png"))); // NOI18N
        jBtnIngresar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Botones/Grandes/entrarGrande.png"))); // NOI18N
        jBtnIngresar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jBtnIngresar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(jBtnIngresar);
        jBtnIngresar.setBounds(240, 270, 120, 110);

        lblTitulo.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        lblTitulo.setText("Acceso al Sistema");
        getContentPane().add(lblTitulo);
        lblTitulo.setBounds(220, 40, 170, 22);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Fondo Grande.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 620, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public JButton getjBtnIngresar(){
        return jBtnIngresar;
    }

    public JComboBox<String> getjComboRoll() {
        return jComboRoll;
    }

    public JPasswordField getjTxtContraseña() {
        return jTxtContraseña;
    }

    /**
     * @param args the command line arguments
     */
    public JTextField getjTxtUsuario() {
        return jTxtUsuario;
    }

    

    public void agregarListener(ActionListener accion) {
        this.jBtnIngresar.addActionListener(accion);
        
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnIngresar;
    private javax.swing.JComboBox<String> jComboRoll;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jTxtContraseña;
    private javax.swing.JTextField jTxtUsuario;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
